### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by quangnguyenbn99** [Eryk96/NetSurfP-3.0#5]
Hello, First of all, Thank you for your contribution very much. However, I'm facing the problem of training with pretrained weight of ESM1b.
Whenever I try to train the NetSurfP3 with the language model from Facebook. It could not run smoothly as NetsurfP2. 
The error is as follows:

> WARNING:setup:"logging.yml" not found. Using basicConfig.
> INFO:nsp3.nsp3.main:Building: nsp3.models.ESM1b
> Traceback (most recent call last):
>   File "/home/quang/.conda/envs/nsp3/bin/nsp3", line 33, in <module>
>     sys.exit(load_entry_point('nsp3', 'console_scripts', 'nsp3')())
>   File "/home/quang/.conda/envs/nsp3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/quang/.conda/envs/nsp3/lib/python3.8/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/quang/.conda/envs/nsp3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/quang/.conda/envs/nsp3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/quang/.conda/envs/nsp3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/ssd1/quang/dti2d/NetSurfP-3.0/nsp3/nsp3/cli.py", line 32, in train
>     main.train(config, resume)
>   File "/ssd1/quang/dti2d/NetSurfP-3.0/nsp3/nsp3/main.py", line 42, in train
>     model = get_instance(module_arch, 'arch', cfg)
>   File "/ssd1/quang/dti2d/NetSurfP-3.0/nsp3/nsp3/main.py", line 285, in get_instance
>     return getattr(module, ctor_name)(*args, **config[name]['args'])
>   File "/ssd1/quang/dti2d/NetSurfP-3.0/nsp3/nsp3/models/ESM1b/model.py", line 23, in __init__
>     self.embedding = ESM1bEmbedding(language_model, **kwargs)
>   File "/ssd1/quang/dti2d/NetSurfP-3.0/nsp3/nsp3/embeddings/esm1b.py", line 42, in __init__
>     alphabet = esm.Alphabet.from_architecture(embedding_args['arch'])
> TypeError: string indices must be integers

looking forward to hearing from you soon!

**Comment by Eryk96** [comment]
Hello Nathaniel,

What is your experiment configuration and what python version of fair-esm are you using?

**Comment by quangnguyenbn99** [comment]
Really sorry for the late reply.
I was trying to run the configuration ESM1b_finetune.yml by python 3.8.8.
However, the code ran smoothly when running with CNNbLSTM_Extended.
